apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-shiva-app
  template:
    metadata:
      labels:
        app: springboot-shiva-app
    spec:
      containers:
        - name: springboot-container-app
          image: springboot-shiva-demo:latest
          ports:
            - containerPort: 8080